name: multibpe
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - bedtools=2.30
  - h5py=2.10
  - meme=5.0
  - numpy=1.19
  - pandas=1.1
  - pip=21.0
  - pybedtools=0.8
  - pytorch=1.8
  - scikit-learn=0.24
  - tqdm=4.7
  - ucsc-bigwigtobedgraph=357
  - pip:
    - pytorch-crf==0.7.2
